# Site settings
title: Suzpack Light
email: sidsmail@gmx.com
description: > # this means to ignore newlines until "baseurl:"
  Cry yourself to sleep lol
baseurl: "suzpack" # the subpath of your site, e.g. /blog/
url: "https://zuzk.github.io/" # the base hostname & protocol for your site
twitter_username: survivaltin
github_username:  zuzk

# Build settings
markdown: kramdown
